import type { AnalyticsReport } from '../../types/analytics.js';
import { ActivitySectionGenerator } from './activity-section.js';
import { ContributorSectionGenerator } from './contributor-section.js';
import { LabelSectionGenerator } from './label-section.js';
import { HealthSectionGenerator } from './health-section.js';
import { RecommendationsGenerator } from './recommendations.js';
import { statusHelpers } from './status-helpers.js';

/**
 * Main class for generating markdown analytics reports
 * Orchestrates all section generators
 */
export class MarkdownReportGenerator {
  private activityGenerator: ActivitySectionGenerator;
  private contributorGenerator: ContributorSectionGenerator;
  private labelGenerator: LabelSectionGenerator;
  private healthGenerator: HealthSectionGenerator;
  private recommendationsGenerator: RecommendationsGenerator;

  constructor() {
    this.activityGenerator = new ActivitySectionGenerator();
    this.contributorGenerator = new ContributorSectionGenerator();
    this.labelGenerator = new LabelSectionGenerator();
    this.healthGenerator = new HealthSectionGenerator();
    this.recommendationsGenerator = new RecommendationsGenerator();
  }

  /**
   * Generate a complete markdown report from analytics data
   */
  async generate(report: AnalyticsReport, packageVersion: string = 'unknown'): Promise<string> {
    let md = '';

    md += this.generateHeader(report);
    md += this.generateExecutiveSummary(report);
    md += this.activityGenerator.generate(report);
    md += this.contributorGenerator.generate(report);
    md += this.labelGenerator.generate(report);
    md += this.healthGenerator.generate(report);
    md += this.recommendationsGenerator.generate(report);
    md += this.generateMetadata(report, packageVersion);
    md += this.generateSummaryStats(report);

    return md;
  }

  /**
   * Generate report header with title and metadata
   */
  private generateHeader(report: AnalyticsReport): string {
    const now = new Date(report.generatedAt);
    let md = `# 📊 Analytics Report\n\n`;
    md += `## ${report.repository}\n\n`;
    md += `**Generated:** ${now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })} at ${now.toLocaleTimeString()}\n\n`;
    md += `---\n\n`;
    return md;
  }

  /**
   * Generate executive summary with key metrics
   */
  private generateExecutiveSummary(report: AnalyticsReport): string {
    let md = `## 📋 Executive Summary\n\n`;
    md += `This comprehensive analytics report analyzes repository activity, contributor patterns, labeling practices, and code health metrics to provide actionable insights.\n\n`;

    // Quick stats box
    md += `### Key Metrics at a Glance\n\n`;
    md += `| Metric | Value | Status |\n`;
    md += `|--------|-------|--------|\n`;
    md += `| **PR Merge Rate** | ${report.activity.prMergeRate.mergeRate.toFixed(1)}% | ${statusHelpers.getHealthStatus(report.activity.prMergeRate.mergeRate, 50, 80)} |\n`;
    md += `| **Review Coverage** | ${report.health.prReviewCoverage.coveragePercentage.toFixed(1)}% | ${statusHelpers.getHealthStatus(report.health.prReviewCoverage.coveragePercentage, 50, 70)} |\n`;
    md += `| **Active Contributors** | ${report.activity.activeContributors[0]?.contributors || 0} | ${statusHelpers.getContributorStatus(report.activity.activeContributors[0]?.contributors || 0)} |\n`;
    md += `| **Bus Factor** | ${report.contributors.busFactor} | ${statusHelpers.getBusFactorStatus(report.contributors.busFactor)} |\n`;
    md += `| **Deployment Frequency** | ${report.health.deploymentFrequency.releases} releases | ${statusHelpers.getDeploymentStatus(report.health.deploymentFrequency.releases)} |\n\n`;
    md += `---\n\n`;

    return md;
  }

  /**
   * Generate report metadata section
   */
  private generateMetadata(report: AnalyticsReport, packageVersion: string): string {
    let md = `---\n\n`;
    md += `## 📚 Report Metadata\n\n`;
    md += `- **Analysis Duration:**\n`;
    md += `  - Activity: ${(report.activity.duration / 1000).toFixed(2)}s\n`;
    md += `  - Contributors: ${(report.contributors.duration / 1000).toFixed(2)}s\n`;
    md += `  - Labels: ${(report.labels.duration / 1000).toFixed(2)}s\n`;
    md += `  - Health: ${(report.health.duration / 1000).toFixed(2)}s\n`;
    md += `- **Generated by:** [GitHub Extractor CLI (ghextractor)](https://github.com/LeSoviet/GithubCLIExtractor)\n`;
    md += `- **Version:** ${packageVersion === 'unknown' ? 'n/a' : packageVersion}\n`;
    return md;
  }

  /**
   * Generate summary statistics section
   */
  private generateSummaryStats(report: AnalyticsReport): string {
    let md = `\n---\n\n`;
    md += `## 📊 Summary Stats\n\n`;
    md += `- **${report.health.prReviewCoverage.total} PRs processed**\n`;
    md += `- **${report.health.prReviewCoverage.reviewed} PRs reviewed**\n`;
    md += `- **${report.health.deploymentFrequency.releases} releases**\n`;
    md += `- **${report.activity.activeContributors[0]?.contributors || 0} active contributors**\n`;

    // Calculate percentage of release-notes labels if available
    const releaseNotesLabel = report.labels.labelDistribution.find(
      (l) => l.label === 'release-notes'
    );
    if (releaseNotesLabel && report.labels.labelDistribution.length > 0) {
      const totalLabels = report.labels.labelDistribution.reduce((sum, l) => sum + l.count, 0);
      const percentage = (releaseNotesLabel.count / totalLabels) * 100;
      md += `- **${percentage.toFixed(1)}% of labels are release-notes**\n`;
    }

    return md;
  }
}
